Repository ligershark/dotnet-new-ui, pull requests merged in 2022-03, with the labels that each got.

#1 Initial Dotnet Bot Command
  .editorconfig
  Source/Directory.Build.props
  Source/DotnetNewUI/Class1.cs
  Source/DotnetNewUI/DotnetNewUI.csproj
  Source/DotnetNewUI/Program.cs
  Tests/DotnetNewUI.Test/Class1Test.cs
Labels: enhancement, minor

#6 Update
  build.cake
Labels: maintenance, patch

#7 Case insensitive
  Source/DotnetNewUI/Frontend/src/views/InstalledView.vue
  Source/DotnetNewUI/Frontend/src/views/SearchView.vue
Labels: enhancement, patch

#9 Cleaning up BuiltInTemplatePackageProvider + PackageInspector
  Source/DotnetNewUI/NuGet/BuiltInTemplatePackageProvider.cs
  Source/DotnetNewUI/NuGet/PackageInspector.cs
  Source/DotnetNewUI/Services/PackagesService.cs
Labels: enhancement, patch
